apps/blog/urls.py
# blog>urls.py

from django.urls import path
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today'),
]

apps/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('uxsample/', include('uxsample.urls')),
    path('blogtutorial/', include('blogtutorial.urls')),
    path('practice01/', include('practice01.urls')),
    path('practice02/', include('practice02.urls')),
    path('stock/', include('stockexample.urls')),
    path('practice03/', include('practice03.urls')),
]

apps/blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    # author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='TITLE', max_length=200)
    content = models.TextField('CONTENT', default='')
    pub_date = models.DateTimeField('PUBLISH DATE', default=timezone.now)
    mod_date = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_post'
        ordering = ('-mod_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.id,))

    def get_previous(self):
        return self.get_previous_by_mod_date()

    def get_next(self):
        return self.get_next_by_mod_date()

apps/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView

from .models import Post

# Create your views here.


class PostLV(ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 3


class PostDV(DetailView):
    model = Post


class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'mod_date'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'mod_date'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'mod_date'
    month_format = '%m'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'mod_date'
    month_format = '%m'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'mod_date'

apps/blog/templates/blog/post_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <p>Post Archives Until {% now "N d, Y" %}</p>

    <ul>
        {% for date in date_list %}
        <li>
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">{{ date|date:'Y' }}</a>
        </li>
        {% endfor %}
    </ul>
    <div></div>
    <div>
        <ul>
            {% for post in object_list %}
            <li>
            {{ post.mod_date|date:"Y-m-d" }}&nbsp;
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>

</body>
</html>

apps/blog/templates/blog/post_archive_day.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <p>Post Archives for {{ day|date:"N d, Y" }}</p>
    <div>
        <ul>
            {% for post in object_list  %}
            <li>{{ post.mod_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
            {% endfor %}

        </ul>
    </div>
</body>
</html>

apps/blog/templates/blog/post_archive_month.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <p>Post Archives for {{ month|date:"N, Y" }}</p>
    <div>
        <ul>
            {% for post in object_list %}
                <li>{{ post.mod_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp; <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
            
            {% endfor %}
            
        </ul>
    </div>
</body>
</html>

apps/blog/templates/blog/post_archive_year.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <p>Post Archives for {{ year|date:"Y" }}</p>
    <ul>
        {% for date in date_list %}
        <li>
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'m' %}">{{ date|date:'F' }}</a>
        </li>
        {% endfor %}
    </ul>
    <div></div>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.mod_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp; <a href="{{ post.get_absolute_usr }}"><strong>{{ post.title }}</strong></a></li>
            {% endfor %}
            
        </ul>
    </div>
</body>
</html>

apps/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog - {{ object.title }}</title>
</head>
<body>

    <p><strong>{{ object.title }}</strong></p>

    <p>
        {% if object.get_previous %}
            <a href="{{ object.get_previous.get_absolute_url }}" title="이전 글">&larr; {{ object.get_previous }} </a>
        {% endif %}

        {% if object.get_next %}
            <a href="{{ object.get_next.get_absolute_url }}" title="다음 글">{{ object.get_next }} &rarr;</a>
        {% endif %}
    </p>

    <p>{{ object.mod_date|date:"j F Y" }}</p>
    <br>
    <br>
    <div>{{ object.content|linebreaks }}</div>
    <div><a href="{% url 'blog:post_list' %}">blog list</a></div>

</body>
</html>

apps/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <h2>Post List</h2>
    <span>
        <a href="{% url 'blog:post_archive' %}">Archive</a>
    </span>

    <p>
        {% for post in posts %}
            <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
            {{ post.mod_date|date:"N d, Y" }}
        {% endfor %}
    </p>
    <br>
    <div>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"> Next Page</a>
        {% endif %} 
    </div>

</body>
</html>