apps/blog/urls.py
# blog>urls.py

from django.urls import path
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today'),
]

apps/blogtutorial/urls.py
from django.urls import path
from . import views

app_name = 'blogtutorial'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

apps/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('uxsample/', include('uxsample.urls')),
    path('blogtutorial/', include('blogtutorial.urls')),
    path('practice01/', include('practice01.urls')),
    path('practice02/', include('practice02.urls')),
    path('stock/', include('stockexample.urls')),
    path('practice03/', include('practice03.urls')),
]

apps/blogtutorial/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.utils import timezone
from ckeditor.fields import RichTextField


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    # text = models.TextField()
    text = RichTextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def __str__(self):
        return self.title

apps/blogtutorial/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

apps/blogtutorial/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm

# Create your views here.
from .models import Post
from django.utils import timezone


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blogtutorial/post_list.html', {'posts': posts})


def post_detail(request,pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blogtutorial/post_detail.html', {'post': post})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blogtutorial:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blogtutorial/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blogtutorial:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blogtutorial/post_edit.html', {'form': form})

apps/blogtutorial/templates/blogtutorial/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Girls Blog</title>

    <link href="{% static 'blogtutorial/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'blogtutorial/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blogtutorial/css/blogtutorial.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

</head>
<body>

    <div class="page-header">
        {% if user.is_authenticated %}
        <a href="{% url 'blogtutorial:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}
        <h1><a href="{% url 'blogtutorial:post_list' %}">Django Girls Blog</a></h1>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>

    </div>


</body>
</html>

apps/blogtutorial/templates/blogtutorial/post_detail.html
{% extends "blogtutorial/base.html" %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                <p>published: {{ post.published_date }}</p>
            </div>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'blogtutorial:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h1><a href="">{{ post.title }}</a></h1>
        <p>{{ post.text|safe|linebreaksbr }}</p>
    </div>
{% endblock %}

apps/blogtutorial/templates/blogtutorial/post_edit.html
{% extends "blogtutorial/base.html" %}

{% block content %}
    <h1>New Post</h1>
    {{ form.media }}
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p|safe }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

apps/blogtutorial/templates/blogtutorial/post_list.html
{% extends "blogtutorial/base.html" %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                <p>published: {{ post.published_date }}</p>
            </div>
            <h1><a href="{% url 'blogtutorial:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|safe|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}