apps/blog/urls.py
# blog>urls.py

from django.urls import path
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today'),
]

apps/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('uxsample/', include('uxsample.urls')),
    path('blogtutorial/', include('blogtutorial.urls')),
    path('practice01/', include('practice01.urls')),
    path('practice02/', include('practice02.urls')),
    path('stock/', include('stockexample.urls')),
    path('practice03/', include('practice03.urls')),
]

apps/practice02/urls.py
from django.urls import path
from . import views

app_name = 'practice02'


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit')
]

apps/practice02/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Post02(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()

apps/practice02/forms.py
from django.forms import ModelForm
from .models import Post02


class Post02Form(ModelForm):

    class Meta:
        model = Post02
        fields = ['title', 'text']

apps/practice02/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .forms import Post02Form
from .models import Post02


def post_list(request):
    posts = Post02.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'practice02/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post02, pk=pk)
    return render(request, 'practice02/post_detail.html', {'post': post})


def post_new(request):
    if request.method == "POST":
        form = Post02Form(request.POST)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.published_date = timezone.now()
            newpost = form.save()
            return redirect('practice02:post_detail', pk=newpost.pk)
    else:
        form = Post02Form()
    return render(request, 'practice02/post_edit.html', {'form': form})


def post_edit(request, pk):
    editpost = get_object_or_404(Post02, pk=pk)
    if request.method == "POST":
        form = Post02Form(request.POST, instance=editpost)
        if form.is_valid():
            editpost = form.save(commit=False)
            editpost.author = request.user
            editpost.published_date = timezone.now()
            editpost = form.save()
            return redirect('practice02:post_detail', pk=editpost.pk)
    else:
        form = Post02Form(instance=editpost)
    return render(request, 'practice02/post_edit.html', {'form': form})

apps/practice02/templates/practice02/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="page-header">
        <p><a href="{% url 'practice02:post_new' %}">Create New Blog +</a></p>
        <h1><a href="{% url 'practice02:post_list' %}">Practice02</a></h1>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

apps/practice02/templates/practice02/post_detail.html
{% extends "practice02/base.html" %}

{% block content %}
    <p>Published: {{ post.published_date }}</p>
    <h1>{{ post.title }}</h1>
    <p>{{ post.text }}</p>
{% endblock %}

apps/practice02/templates/practice02/post_edit.html
{% extends "practice02/base.html" %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">submit</button>
    </form>
{% endblock %}

apps/practice02/templates/practice02/post_list.html
{% extends "practice02/base.html" %}

{% block content %}
    {% for post in posts %}
        <p>Published: {{ post.published_date }}</p>
        <h1><a href="{% url 'practice02:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <button><a href="{% url 'practice02:post_edit' pk=post.pk %}">edit</a></button>
        <p>{{ post.text }}</p>
    {% endfor %}
{% endblock %}